### ISSUE TITLE
How to set shfmt arguments?

### ISSUE THREAD

**Issue by aburlot** [purcell/emacs-shfmt#12]
I am not able to add an argument with the dedicated variable. How am I supposed to write it? If I put `"-i 4"` or `"--indent 4"` or `("--indent" "4")` in the String cell using Customize Group, I have an error `-filename can only be used with stdin`. I am using the `20240104.1218` version. If I put 
```elisp
# Local Variables:
# shfmt-arguments: ("--indent" "4")
# End:
```
it works. Any idea on what am I missing?

**Comment by purcell** [comment]
Each string in the var is a single argument, so use the "INS" button on the Customize widget to add multiple args, like this:

<img width="571" alt="Screenshot 2024-10-30 at 10 32 28" src="https://github.com/user-attachments/assets/5a344d35-5bde-4ede-84e6-54fadf824046">

**Comment by aburlot** [comment]
Thanks, I thought I tested everything :/ works like a charm!
