### ISSUE TITLE
[feature request] using shfmt as default indent function in sh-mode

### ISSUE THREAD

**Issue by braoult** [purcell/emacs-shfmt#2]
Would it be possible to use shfmt as default for all indent functions for shell scripts ?

Maybe a couple of lines in init.el could do it, without changing the code, in this case giving an example of such config would be useful, I think.

If yes, using all common sh-mode variables would be a "plus" (indent-tabs-mode, sh-basic-offset,        comment-column, comment-auto-fill-only-comments, fill-column - I can miss some that I don't use).

Why this request ? Because of this bug that seems ignored by core emacs developers:
[https://debbugs.gnu.org/cgi/bugreport.cgi?bug=40076](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=40076)

**Comment by purcell** [comment]
> Would it be possible to use shfmt as default for all indent functions for shell scripts ?

No, I don't expect so. Formatters like these typically expect to be applied to well-formed source, while emacs indentation is often (or usually) applied to incomplete source.

**Comment by braoult** [comment]
ok. I tried :)
