### ISSUE TITLE
Pass `-filename` argument for file-visiting buffers

### ISSUE THREAD

**Issue by sir4ur0n** [purcell/emacs-shfmt#5]
Currently `shfmt.el` only applies the top level `[*]` pattern of `.editorconfig` files because it calls `shfmt` with `stdin`, thus `shfmt` has no way to know the file name/path to match the right EditorConfig pattern.

`shfmt` supports a `-filename` argument exactly for that purpose.

Would you mind passing that argument for file-visiting buffers please? :pray:

**Comment by purcell** [comment]
How about this?
```
(reformatter-define shfmt
  :program shfmt-command
  :args (append (list "-filename" (or (buffer-file-name) input-file)) shfmt-arguments)
  :lighter " ShFmt"
  :group 'shfmt)
```

**Comment by sir4ur0n** [comment]
It seems to work :+1:
