### ISSUE TITLE
Broken for me (emacs 29)

### ISSUE THREAD

**Issue by port19x** [purcell/emacs-shfmt#9]
Doesn't correctly pass `-i 4` but even without that, in a configuration that does run shfmt, it just clears the buffer upon any shfmt invocation.
Reproduced with `shfmt-buffer` and the on-save hook.

My desired args are `-i 4 -ci -d`.
Shell script in question is [ani-cli](github.com/pystardust/ani-cli)

**Comment by purcell** [comment]
Thanks, confirmed and fixed.

**Comment by purcell** [comment]
I think `shfmt` must have normalised its command line args so that long options not begin with `--`: the arg used to be called `-filename` last year. Thanks for the bug report.

**Comment by port19x** [comment]
Waiting for melpa to sync, will confirm later today

**Comment by purcell** [comment]
I forced a rebuild just now

**Comment by port19x** [comment]
Can't confirm as fixed with version `20240104.1117` which I assume to be the rebuild

**Comment by port19x** [comment]
Maybe I need to reload stuff, I'll restart emacs for good measure

**Comment by port19x** [comment]
Seems to be still broken for me. Same behavour with the buffer clearing as previously.

**Comment by purcell** [comment]
How are you setting the args. I've noticed that if you set the args the wrong way, it leads to lisp errors that might not be visible. For example:
```el
# Local Variables:
# shfmt-arguments: '("-i" "4")
# End:
```
fails because it should be
```el
# Local Variables:
# shfmt-arguments: ("-i" "4")
# End:
```
(note the lack of single quote)

**Comment by purcell** [comment]
I'm taking a look using your settings (from the other PR) and that specific script.

**Comment by purcell** [comment]
Okay, I think the problem is that you're passing `-d` which is a run mode that doesn't do the right thing. When run, shfmt is expected to output the reformatted version of its input text. `-d` tells it to assert that no reformatting is necessary, and to error out with a diff if the assertion fails. So the fix should be to just remove that arg.

**Comment by purcell** [comment]
I added a note to the docstring for `shfmt-arguments`.

**Comment by port19x** [comment]
Thx, that should be it. I just blindly copied the args from the CI pipeline :sweat_smile:

**Comment by port19x** [comment]
Yep, everything works as it should

**Comment by purcell** [comment]
Great, happy it's working for you
